## Word Embeddings

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
#The indices of the words represent the values in the lookup table
word_to_idx = {"I": 0, "love": 1, "eating":2, "and":3, "sleeping":4}
embeddings = nn.Embedding(5, 7)    # 5 words in vocab, embedding size is 7
word_index = torch.tensor([word_to_idx["love"]])
print(word_index)

tensor([1])


In [3]:
love = embeddings(word_index)
print(love)
print(love.shape)

tensor([[ 0.0542, -0.5999, -0.9556, -0.7349, -1.0816, -2.2142,  0.3905]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([1, 7])


In [4]:
all_ind = torch.tensor([w for w in range(5)], dtype = torch.long)
all_words = embeddings(all_ind)
print(all_ind)
print(all_words)
print(all_words.shape)

tensor([0, 1, 2, 3, 4])
tensor([[-0.4282, -1.2600, -1.1115,  0.1841,  1.0841, -1.6038, -1.3816],
        [ 0.0542, -0.5999, -0.9556, -0.7349, -1.0816, -2.2142,  0.3905],
        [-0.4083, -0.9367,  0.9167, -1.0451,  1.2116, -0.8265, -0.6874],
        [-1.0161,  1.4015, -1.7618, -0.1211,  0.0432, -0.3160,  1.5329],
        [-0.0814, -2.4030, -2.4079,  1.0995, -1.1535, -1.0737, -0.6146]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([5, 7])


## Exercise: N-Gram Skip Model
### Given a sequence of words, we want to predict the ith word of the sequence: P(w(i)|w(i-1), w(i-2), .....)
#### Source: https://pytorch.org/tutorials/beginner/nlp/word_embeddings_tutorial.html#an-example-n-gram-language-modeling  
